AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: True Profit MVP - Backend & Pipeline

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 256

Resources:

  ############################
  # 1. DynamoDB Tables
  ############################

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Transactions
      PrimaryKey:
        Name: transaction_id
        Type: String
      # BillingMode: PAY_PER_REQUEST

  MerchantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Merchants
      PrimaryKey:
        Name: merchant_id
        Type: String
      # BillingMode: PAY_PER_REQUEST

  DailyMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DailyMetrics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: merchant_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: merchant_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE

  MarketingSpendTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MarketingSpend
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: merchant_id
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: merchant_id
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE

  ############################
  # 2. SQS + DLQ + CLoudWatch
  ############################

  DeadLetterQueue:
    Type: AWS::SQS::Queue

  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  DeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value: !GetAtt DeadLetterQueue.QueueName
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AlertTopic

  ############################
  # 3. S3 Export Bucket
  ############################

  ExportBucket:
    Type: AWS::S3::Bucket

  ############################
  # 4. SNS (Demo / Alert)
  ############################

  AlertTopic:
    Type: AWS::SNS::Topic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: your_email@example.com

  ############################
  # 5. Ingest Lambda
  ############################

  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/ingest/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          QUEUE_URL: !Ref IngestionQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt IngestionQueue.QueueName
      Events:
        IngestApi:
          Type: Api
          Properties:
            Path: /ingest/transaction
            Method: POST

  ############################
  # 6. Processor Lambda (CORE)
  ############################

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/processor
      Handler: handler.lambda_handler
      Environment:
        Variables:
          TRANSACTIONS_TABLE: !Ref TransactionsTable
          DAILY_METRICS_TABLE: !Ref DailyMetricsTable
          EXPORT_BUCKET: !Ref ExportBucket
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt IngestionQueue.Arn
            BatchSize: 10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt TransactionsTable.Arn
            - Effect: Allow
              Action:
               - dynamodb:UpdateItem
               - dynamodb:GetItem
              Resource: !GetAtt DailyMetricsTable.Arn
        - SQSPollerPolicy:
            QueueName: !GetAtt IngestionQueue.QueueName
        - S3WritePolicy:
            BucketName: !Ref ExportBucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AlertTopic.TopicName

Outputs:

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  IngestTransactionEndpoint:
    Description: Ingest transaction endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ingest/transaction"

  IngestionQueueUrl:
    Description: SQS Queue URL
    Value: !Ref IngestionQueue
